Update README.md
missCarrieMah/GHC-Events pull request #1
Opened 2017-09-05 22:57 UTC by amonseth

thanks!

2017-09-05 23:23 UTC, missCarrieMah commented
Thanks for reading :)!

2017-09-05 23:34 UTC, craftypixeldesigns requested changes
Thanks for the update! Just a small note on making the "Notes" a tad shorter.

2017-09-05 23:34 UTC, missCarrieMah commented on README.md
> +| [Women in Tech Workshop sponsored by Target](https://www.linkedin.com/pulse/women-tech-workshop-grace-hopper-sponsored-target-ashley-monseth) | [Target](https://www.codewithtarget.com) | upon RSVP|
Thanks for fixing that link! I think I spaced out when I copy & pasted text :)

For concise notes, would it be possible to modify the notes to:
`RSVP Email [Ashley](mailto:ashley.monseth@target.com)`

I like the "Upon RSVP" comment, thanks for adding that!

2017-09-06 17:00 UTC, craftypixeldesigns approved these changes

2017-09-06 17:01 UTC, merged